Controllers/TopController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tec_parts_supply_transport_web.Models;

namespace tec_parts_supply_transport_web.Controllers
{
    public class TopController : Controller
    {
        private readonly ILogger<TopController> _logger;

        public TopController(ILogger<TopController> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// トップ画面表示
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>@ViewData["Title"] - 空箱供給運搬アプリ</title>
    <!-- ▼ファビコン -->
    <link rel="shortcut icon" type="image/png" href="~/images\icon_app.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/images\icon_app.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/tec_parts_supply_transport_web.styles.css" asp-append-version="true" />*@
</head>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.31/dist/sweetalert2.all.min.js"></script>
@{
    if (@ViewData["Title"] != "トップ")
    {
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <style>
            html {
                background: #000000;
            }
        </style>
    }
}


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow nav-head">
            <div class="container-fluid justify-content-between">
                @{
                    if (@ViewData["Title"] == "部品準備" || @ViewData["Title"] == "部品運搬")
                    {
                        <div class="d-flex justify-content-center align-items-center header-title h2">@ViewData["Title"]</div>
                        <a class="navbar-brand home-icon" asp-area="" asp-controller="Top" asp-action="Index"><i class="fa fa-fw fa-home"></i></a>
                    }
                    else
                    {
                        <div class="d-flex justify-content-center align-items-center header-title h2">@ViewData["Title"]</div>
                    }
                }
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @{
        if (@ViewData["Title"] == "トップ")
        {
            <div class="version-info">ver.1.2</div>
        }
    }

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>